version: 0.2

phases:
  install:
    commands:
      - dotnet tool install -g Amazon.ElasticBeanstalk.Tools
  build:
    commands:
      - cd ExampleNETCoreDeployWithAWSCodePipeline
      - dotnet eb package
artifacts:
  files:
    - ./ExampleNETCoreDeployWithAWSCodePipeline/bin/Release/netcoreapp2.1/publish/*
  discard-paths: yes